package br.dwws.labwork.classiweb.core.application;

import java.io.Serializable;
import java.util.Collection;
import javax.ejb.Local;
import br.dwws.labwork.classiweb.core.domain.Anuncio;
import br.dwws.labwork.classiweb.core.domain.Endereco;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface AnuncioService extends Serializable {

  /** TODO: generated by FrameWeb. Should be documented. */
  public void cadastrarAnuncio(Anuncio anuncio);

  /** TODO: generated by FrameWeb. Should be documented. */
  public Collection filtrarAnuncios(Collection categorias, Endereco localidade, Float precoMinimo,
      Float precoMaximo, String titulo, String descricao);

}
