package br.dwws.labwork.classiweb.core.application;

import java.io.Serializable;
import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface CompraFinalizadaService extends Serializable {

}
