package br.dwws.labwork.classiweb.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;
import br.dwws.labwork.classiweb.core.domain.Anuncio;
import br.dwws.labwork.classiweb.core.domain.UsuarioComum;
import br.dwws.labwork.classiweb.core.persistence.CompraFinalizadaDAO;
import br.dwws.labwork.classiweb.core.persistence.UsuarioComumDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class CompraFinalizadaBean implements CompraFinalizada {
  /** Serialization id (using default value, change if necessary). */
  private static final long serialVersionUID = 1L;


  /** TODO: generated by FrameWeb. Should be documented. */
  @EJB
  private CompraFinalizadaDAO compraFinalizadaDAO;

  /** TODO: generated by FrameWeb. Should be documented. */
  @EJB
  private UsuarioComumDAO usuarioComumDAO;



  /** TODO: generated by FrameWeb. Should be documented. */
  @Override
  public void finalizarCompra(UsuarioComum cliente, Anuncio anuncio) {
    // FIXME: auto-generated method stub
    return;
  }

  /** TODO: generated by FrameWeb. Should be documented. */
  @Override
  public void realizarAvaliacao() {
    // FIXME: auto-generated method stub
    return;
  }

}
