import ServicesDocs from './src/application/ServicesDocs';
import { port } from './src/index';

const swaggerAutogen = require('swagger-autogen')();

const documentation = {
  info: {
    version: '1.0.0',
    title: 'ClassiWeb API',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },

  host: `localhost:${port}`,
  basePath: '/',

  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],

  securityDefinitions: {
    apiKeyAuth: {
      type: 'apiKey',
      in: 'header', // can be "header", "query" or "cookie"
      name: 'X-API-KEY', // name of the header, query parameter or cookie
      description: 'any description...',
    },
  },

  tags: ServicesDocs.map(({ tag }) => tag),
  definitions: ServicesDocs.reduce((result, doc) => ({ ...result, ...doc.definitions }), {}),
};

const outputFile = './src/swagger_output.json';
const endpointsFiles = ['./src/index.ts'];

swaggerAutogen(outputFile, endpointsFiles, documentation).then(() => {
  import('./src/index'); // Your project's root file
});
