package br.dwws.labwork.classiweb.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class CadastroAnuncioController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private AnuncioService anuncioService;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Anuncio anuncio;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Endereco endereco;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Categoria categoria;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String cadastrarAnuncio() {
		// FIXME: auto-generated method stub
		return null;
	}
	
	
	
	/** Getter for anuncio. */
	public Anuncio getAnuncio() {
		return anuncio;
	}

	/** Setter for anuncio. */
	public void setAnuncio(Anuncio anuncio) {
		this.anuncio = anuncio;
	}
	
	/** Getter for endereco. */
	public Endereco getEndereco() {
		return endereco;
	}

	/** Setter for endereco. */
	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}
	
	/** Getter for categoria. */
	public Categoria getCategoria() {
		return categoria;
	}

	/** Setter for categoria. */
	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}
	
}