package br.dwws.labwork.classiweb.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;
import br.dwws.labwork.classiweb.core.application.CompraFinalizadaService;
import br.dwws.labwork.classiweb.core.domain.Anuncio;
import br.dwws.labwork.classiweb.core.domain.UsuarioComum;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class CompraFinalizadaController extends JSFController {
  /** Serialization id (using default value, change if necessary). */
  private static final long serialVersionUID = 1L;


  /** TODO: generated by FrameWeb. Should be documented. */
  @EJB
  private CompraFinalizadaService compraFinalizadaService;



  /** TODO: generated by FrameWeb. Should be documented. */
  private Anuncio anuncio;

  /** TODO: generated by FrameWeb. Should be documented. */
  private UsuarioComum cliente;



  /** TODO: generated by FrameWeb. Should be documented. */
  public void realizarCompra() {
    // FIXME: auto-generated method stub
    return;
  }



  /** Getter for anuncio. */
  public Anuncio getAnuncio() {
    return anuncio;
  }

  /** Setter for anuncio. */
  public void setAnuncio(Anuncio anuncio) {
    this.anuncio = anuncio;
  }

  /** Getter for cliente. */
  public UsuarioComum getCliente() {
    return cliente;
  }

  /** Setter for cliente. */
  public void setCliente(UsuarioComum cliente) {
    this.cliente = cliente;
  }

}
