package br.dwws.labwork.classiweb.core.controller;

import java.util.Collection;
import javax.ejb.EJB;
import javax.enterprise.inject.Model;
import br.dwws.labwork.classiweb.core.application.AnuncioService;
import br.dwws.labwork.classiweb.core.domain.Endereco;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class FiltrarAnuncioController extends JSFController {
  /** Serialization id (using default value, change if necessary). */
  private static final long serialVersionUID = 1L;


  /** TODO: generated by FrameWeb. Should be documented. */
  @EJB
  private AnuncioService anuncioService;



  /** TODO: generated by FrameWeb. Should be documented. */
  private Endereco localidade;

  /** TODO: generated by FrameWeb. Should be documented. */
  private Collection categorias;

  /** TODO: generated by FrameWeb. Should be documented. */
  private Float precoMinimo;

  /** TODO: generated by FrameWeb. Should be documented. */
  private Float precoMaximo;

  /** TODO: generated by FrameWeb. Should be documented. */
  private String titulo;

  /** TODO: generated by FrameWeb. Should be documented. */
  private String descricao;



  /** TODO: generated by FrameWeb. Should be documented. */
  public Collection filtrarAnuncios() {
    // FIXME: auto-generated method stub
    return null;
  }



  /** Getter for localidade. */
  public Endereco getLocalidade() {
    return localidade;
  }

  /** Setter for localidade. */
  public void setLocalidade(Endereco localidade) {
    this.localidade = localidade;
  }

  /** Getter for categorias. */
  public Collection getCategorias() {
    return categorias;
  }

  /** Setter for categorias. */
  public void setCategorias(Collection categorias) {
    this.categorias = categorias;
  }

  /** Getter for precoMinimo. */
  public Float getPrecoMinimo() {
    return precoMinimo;
  }

  /** Setter for precoMinimo. */
  public void setPrecoMinimo(Float precoMinimo) {
    this.precoMinimo = precoMinimo;
  }

  /** Getter for precoMaximo. */
  public Float getPrecoMaximo() {
    return precoMaximo;
  }

  /** Setter for precoMaximo. */
  public void setPrecoMaximo(Float precoMaximo) {
    this.precoMaximo = precoMaximo;
  }

  /** Getter for titulo. */
  public String getTitulo() {
    return titulo;
  }

  /** Setter for titulo. */
  public void setTitulo(String titulo) {
    this.titulo = titulo;
  }

  /** Getter for descricao. */
  public String getDescricao() {
    return descricao;
  }

  /** Setter for descricao. */
  public void setDescricao(String descricao) {
    this.descricao = descricao;
  }

}
