package br.dwws.labwork.classiweb.core.persistence;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class AnuncioDAOJPA extends BaseJPADAO<Anuncio> implements AnuncioDAO{
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
    @PersistenceContext
    private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}
    
    
	/** TODO: generated by FrameWeb. Should be documented. */
    @Override
	public void cadastrarAnuncio(Anuncio anuncio) {
		// FIXME: auto-generated method stub
		return;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
    @Override
	public Collection filtrarAnuncios(Collection categorias, Endereco localidade, Float precoMinimo, Float precoMaximo, String titulo, String descricao) {
		// FIXME: auto-generated method stub
		return null;
	}
	

}