package br.dwws.labwork.classiweb.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class CompraFinalizada extends PersistentObjectSupport implements Comparable<CompraFinalizada> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private Date data;

	/** TODO: generated by FrameWeb. Should be documented. false */
	  
	private RankingFeedback avaliacaoVendedor;

	/** TODO: generated by FrameWeb. Should be documented. false */
	  
	private RankingFeedback avaliacaoComprador;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private UsuarioComum Target;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private Anuncio Target;
		
	




	/** Getter for data. */
	public Date getData() {
		return data;
	}
	
	/** Setter for data. */
	public void setData(Date data) {
		this.data = data;
	}

	/** Getter for avaliacaoVendedor. */
	public RankingFeedback getAvaliacaoVendedor() {
		return avaliacaoVendedor;
	}
	
	/** Setter for avaliacaoVendedor. */
	public void setAvaliacaoVendedor(RankingFeedback avaliacaoVendedor) {
		this.avaliacaoVendedor = avaliacaoVendedor;
	}

	/** Getter for avaliacaoComprador. */
	public RankingFeedback getAvaliacaoComprador() {
		return avaliacaoComprador;
	}
	
	/** Setter for avaliacaoComprador. */
	public void setAvaliacaoComprador(RankingFeedback avaliacaoComprador) {
		this.avaliacaoComprador = avaliacaoComprador;
	}




		
		/** Getter for Target. */
		public UsuarioComum getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(UsuarioComum Target) {
			this.Target = Target;
		}
		
	

		
		/** Getter for Target. */
		public Anuncio getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Anuncio Target) {
			this.Target = Target;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(CompraFinalizada o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}