package br.dwws.labwork.classiweb.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class UsuarioCadastrado extends PersistentObjectSupport implements Comparable<UsuarioCadastrado> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String senha;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String email;







	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for senha. */
	public String getSenha() {
		return senha;
	}
	
	/** Setter for senha. */
	public void setSenha(String senha) {
		this.senha = senha;
	}

	/** Getter for email. */
	public String getEmail() {
		return email;
	}
	
	/** Setter for email. */
	public void setEmail(String email) {
		this.email = email;
	}








	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(UsuarioCadastrado o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}