package br.dwws.labwork.classiweb.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class UsuarioComum extends PersistentObjectSupport implements Comparable<UsuarioComum> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String cpf;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne(mappedBy="Target")
		private  Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne(mappedBy="Target")
		private  Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Target")
		private Set<Anuncio> Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Target")
		private Set<CompraFinalizada> Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToMany
		private Set<Anuncio> Target;
		
	




	/** Getter for cpf. */
	public String getCpf() {
		return cpf;
	}
	
	/** Setter for cpf. */
	public void setCpf(String cpf) {
		this.cpf = cpf;
	}




		
		/** Getter for Source. */
		public  getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource( Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Source. */
		public  getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource( Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Source. */
		public Set<Anuncio> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<Anuncio> Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Source. */
		public Set<CompraFinalizada> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<CompraFinalizada> Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Target. */
		public Set<Anuncio> getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Set<Anuncio> Target) {
			this.Target = Target;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(UsuarioComum o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}