package br.dwws.labwork.classiweb.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Categoria extends PersistentObjectSupport implements Comparable<Categoria> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String descricao;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Target")
		private Set<Anuncio> Source;
		
	




	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for descricao. */
	public String getDescricao() {
		return descricao;
	}
	
	/** Setter for descricao. */
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}




		
		/** Getter for Source. */
		public Set<Anuncio> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<Anuncio> Source) {
			this.Source = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Categoria o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}