package br.dwws.labwork.classiweb.core.domain;

import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Endereco extends PersistentObjectSupport implements Comparable<Endereco> {
  /** Serialization id. */
  private static final long serialVersionUID = 1L;



  /** TODO: generated by FrameWeb. Should be documented. false */
  @NotNull
  private String cidade;

  /** TODO: generated by FrameWeb. Should be documented. false */
  @NotNull
  private String estado;



  /** TODO: generated by FrameWeb. Should be documented. */
  @OneToOne(mappedBy = "Target")
  private Anuncio Source;



  /** TODO: generated by FrameWeb. Should be documented. */
  @OneToMany(mappedBy = "Source")
  private Set<> Target;



  /** TODO: generated by FrameWeb. Should be documented. */
  @OneToMany(mappedBy = "Target")
  private Set<Anuncio> Source;



  /** Getter for cidade. */
  public String getCidade() {
    return cidade;
  }

  /** Setter for cidade. */
  public void setCidade(String cidade) {
    this.cidade = cidade;
  }

  /** Getter for estado. */
  public String getEstado() {
    return estado;
  }

  /** Setter for estado. */
  public void setEstado(String estado) {
    this.estado = estado;
  }



  /** Getter for Source. */
  public Anuncio getSource() {
    return Source;
  }

  /** Setter for Source. */
  public void setSource(Anuncio Source) {
    this.Source = Source;
  }



  /** Getter for Target. */
  public Set<> getTarget() {
    return Target;
  }

  /** Setter for Target. */
  public void setTarget(Set<> Target) {
    this.Target = Target;
  }



  /** Getter for Source. */
  public Set<Anuncio> getSource() {
    return Source;
  }

  /** Setter for Source. */
  public void setSource(Set<Anuncio> Source) {
    this.Source = Source;
  }



  /** @see java.lang.Comparable#compareTo(java.lang.Object) */
  @Override
  public int compareTo(Endereco o) {
    // FIXME: auto-generated method stub
    return super.compareTo(o);
  }
}
