package br.dwws.labwork.classiweb.core.domain;

/** TODO: generated by FrameWeb. Should be documented. */
public enum RankingFeedback {
	muitoInsatisfeito, insatisfeito, indiferente, satisfeito, muitoSatisfeito;
}